name: Preload cache

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  curl_urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for 30 seconds
        run: |
          sleep 30s

      - name: Execute curl script
        run: |
          chmod +x script.sh 
          ./script.sh
