name: Hit URLs with Curl

on:
  push:
    branches:
      - main

jobs:
  curl_urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for 2 minutes
        run: |
          sleep 30s

      - name: Execute curl script
        run: |
          chmod +x script.sh 
          ./script.sh
